### ISSUE TITLE
Use singular page objects

### ISSUE THREAD

**Issue by celodauane** [ThomasHansson/Appium-cross-platform-example#1]
Hi

I really liked the way you set up your appium project. However, why did you prefer two have 2 page objects for each screen (Android and iOS), instead of using a singular object with @AndroidFindBy and @iOSFindBy methods? E.g https://blog.jayway.com/2016/06/30/cross-platform-testing-example-android-ios-using-appium/

**Comment by ThomasHansson** [comment]
Hi.

If the app you are testing is performing the exact same way in Android and iOS that would be the best approach to just have a single page object file using the @AndroidFindBy and @iOSFindBy annotations.
But there are often small deviations between the platforms for performing the same task. E.g. in my simple example project, when performing search, I can in Android directly send the string to the search field. But for iOS i first need to "enable" the search field by clicking it in order to send the string to it. And in my experience there are often these small deviations between how the app behaves in the different platforms. And my solution to "get around" this is is to instead implement an interface for each page under test that defines the methods used in the tests. Then the platform specific page object files implements that interface methods in their own way.

**Comment by celodauane** [comment]
Hi

You are completely right. It is very rare that the apps will behave in the exact same manner. Your workaround is pretty good. I liked it.

Keep up with the good work.
